### ISSUE TITLE
build fail after updated to 2.1.1

### ISSUE THREAD

**Issue by zhenjun115** [ant-design/ant-design-pro#3259]
```
 error  in ./src/pages/Profile/AdvancedProfile.less

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):
Error: Cannot find module 'less'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/zhenjun/Public/contract-manager/node_modules/less-loader/dist/index.js:7:13)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Module._compile (/Users/zhenjun/Public/contract-manager/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Object.newLoader [as .js] (/Users/zhenjun/Public/contract-manager/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/zhenjun/Public/contract-manager/node_modules/less-loader/dist/cjs.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at runLoaders (/Users/zhenjun/Public/contract-manager/node_modules/webpack/lib/NormalModule.js:301:20)
    at /Users/zhenjun/Public/contract-manager/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/zhenjun/Public/contract-manager/node_modules/loader-runner/lib/LoaderRunner.js:170:18
    at loadLoader (/Users/zhenjun/Public/contract-manager/node_modules/loader-runner/lib/loadLoader.js:27:11)
    at iteratePitchingLoaders (/Users/zhenjun/Public/contract-manager/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/zhenjun/Public/contract-manager/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/zhenjun/Public/contract-manager/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/zhenjun/Public/contract-manager/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/zhenjun/Public/contract-manager/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/zhenjun/Public/contract-manager/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/zhenjun/Public/contract-manager/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/zhenjun/Public/contract-manager/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/zhenjun/Public/contract-manager/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/zhenjun/Public/contract-manager/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/zhenjun/Public/contract-manager/node_modules/webpack/lib/NormalModule.js:280:3)
    at NormalModule.build (/Users/zhenjun/Public/contract-manager/node_modules/webpack/lib/NormalModule.js:427:15)

 @ ./src/pages/Profile/AdvancedProfile.js 90:46-79
 @ ./src/pages/.umi/router.js
 @ ./src/pages/.umi/umi.js
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js
```

**Comment by chenshuai2144** [comment]
这个是 less 包不存在的问题。你需要重新安装一下 npm 包。建议使用 cnpm
